{% set version = "2.0.6" %}

package:
  name: bob.ip.draw
  version: {{ version }}

source:
  fn: bob.ip.draw-{{ version }}.zip
  md5: f7fc6c05d392d89278ac75987c1ecdf1
  url: https://pypi.io/packages/source/b/bob.ip.draw/bob.ip.draw-{{ version }}.zip

build:
  number: 0
  skip: true  # [win]
  script: python -B setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - bob.extension >2.0.4
    - bob.blitz
    - pkg-config

  run:
    - python
    - bob.extension >2.0.4
    - bob.blitz

test:
  commands:
    - nosetests -sv bob.ip.draw

  imports:
    - bob
    - bob.ip
    - bob.ip.draw

  requires:
    - nose

about:
  home: https://www.idiap.ch/software/bob/
  license: Modified BSD License (3-clause)
  summary: Line and Box drawing utilities of Bob

extra:
  recipe-maintainers:
    - 183amir
